version: "3.8"
services:

  website-checker:
    build:
      context: srv/website-checker
      dockerfile: Dockerfile
    command: uvicorn app.main:application --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./srv/website-checker/src:/opt/app/src

  monitoring-writer:
    build:
      context: srv/monitoring-writer
      dockerfile: Dockerfile
    command: python -m sitemonitor.reload
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PG_HOST}:5432/${POSTGRES_DB}
      - TEST_DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PG_HOST}:5432/${TESTING_DB}
    depends_on:
      - backend-db
    volumes:
      - ./srv/monitoring-writer/src:/opt/app/src

  backend-db:
    build:
      context: srv/db
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  default:
    external:
      name: development

volumes:
  postgres_data:
